import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "fs";
import path from "path";
import type { Plugin } from "vite";

/**
 * Scans public/images/partners at build/dev time and writes
 * src/.generated/partner-logos.ts: one entry per valid logo image, with its
 * real pixel size. The site therefore shows EVERY logo in that folder without
 * a hand-maintained list, and each <img> can reserve its exact space (no
 * layout shift). Dropping a new logo into the folder is enough; in dev the
 * list refreshes by itself, in a build it is regenerated.
 */

const LOGO_DIR = "public/images/partners";
const GENERATED = "src/.generated/partner-logos.ts";
const EXTENSIONS = new Set([".png", ".webp", ".svg", ".jpg", ".jpeg", ".gif"]);

export interface LogoFile {
  file: string;
  width: number;
  height: number;
}

function pngSize(b: Buffer): [number, number] | null {
  if (b.length < 24 || b.toString("latin1", 1, 4) !== "PNG") return null;
  return [b.readUInt32BE(16), b.readUInt32BE(20)];
}

function gifSize(b: Buffer): [number, number] | null {
  if (b.length < 10 || b.toString("latin1", 0, 3) !== "GIF") return null;
  return [b.readUInt16LE(6), b.readUInt16LE(8)];
}

function webpSize(b: Buffer): [number, number] | null {
  if (b.length < 30 || b.toString("latin1", 0, 4) !== "RIFF" || b.toString("latin1", 8, 12) !== "WEBP") return null;
  const kind = b.toString("latin1", 12, 16);
  if (kind === "VP8 ") return [b.readUInt16LE(26) & 0x3fff, b.readUInt16LE(28) & 0x3fff];
  if (kind === "VP8L") {
    const w = 1 + (((b[22] & 0x3f) << 8) | b[21]);
    const h = 1 + (((b[24] & 0x0f) << 10) | (b[23] << 2) | ((b[22] & 0xc0) >> 6));
    return [w, h];
  }
  if (kind === "VP8X") return [1 + b.readUIntLE(24, 3), 1 + b.readUIntLE(27, 3)];
  return null;
}

function jpegSize(b: Buffer): [number, number] | null {
  if (b.length < 4 || b[0] !== 0xff || b[1] !== 0xd8) return null;
  let i = 2;
  while (i + 9 < b.length) {
    if (b[i] !== 0xff) {
      i += 1;
      continue;
    }
    const marker = b[i + 1];
    const isFrame = marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc;
    if (isFrame) return [b.readUInt16BE(i + 7), b.readUInt16BE(i + 5)];
    i += 2 + b.readUInt16BE(i + 2);
  }
  return null;
}

function svgSize(b: Buffer): [number, number] | null {
  const head = b.toString("utf8", 0, Math.min(b.length, 4096));
  const tag = head.match(/<svg[^>]*>/i)?.[0];
  if (!tag) return null;
  const viewBox = tag.match(/viewBox\s*=\s*["']\s*[-\d.]+[\s,]+[-\d.]+[\s,]+([\d.]+)[\s,]+([\d.]+)/i);
  if (viewBox) return [parseFloat(viewBox[1]), parseFloat(viewBox[2])];
  const w = tag.match(/\swidth\s*=\s*["']([\d.]+)/i);
  const h = tag.match(/\sheight\s*=\s*["']([\d.]+)/i);
  return w && h ? [parseFloat(w[1]), parseFloat(h[1])] : null;
}

export function imageSize(file: string, data: Buffer): [number, number] | null {
  const ext = path.extname(file).toLowerCase();
  const size =
    ext === ".png" ? pngSize(data)
    : ext === ".webp" ? webpSize(data)
    : ext === ".svg" ? svgSize(data)
    : ext === ".gif" ? gifSize(data)
    : jpegSize(data);
  return size && size[0] > 0 && size[1] > 0 ? size : null;
}

/** Natural sort, so imgi_6 comes before imgi_10. */
const collator = new Intl.Collator("en", { numeric: true, sensitivity: "base" });

export function scanLogos(root: string): { logos: LogoFile[]; skipped: string[] } {
  const dir = path.join(root, LOGO_DIR);
  const logos: LogoFile[] = [];
  const skipped: string[] = [];
  let names: string[] = [];
  try {
    names = readdirSync(dir);
  } catch {
    return { logos, skipped };
  }
  for (const file of names.sort(collator.compare)) {
    if (!EXTENSIONS.has(path.extname(file).toLowerCase())) {
      skipped.push(file);
      continue;
    }
    const size = imageSize(file, readFileSync(path.join(dir, file)));
    if (!size) {
      skipped.push(file);
      continue;
    }
    logos.push({ file, width: Math.round(size[0] * 100) / 100, height: Math.round(size[1] * 100) / 100 });
  }
  return { logos, skipped };
}

function render(logos: LogoFile[]): string {
  const rows = logos
    .map((l) => `  { file: ${JSON.stringify(l.file)}, width: ${l.width}, height: ${l.height} },`)
    .join("\n");
  return `// AUTO-GENERATED by partnerLogosPlugin.ts from ${LOGO_DIR}. Do not edit by hand.\nexport const partnerLogoFiles: ReadonlyArray<{ file: string; width: number; height: number }> = [\n${rows}\n];\n`;
}

export function partnerLogosPlugin(): Plugin {
  let root = "";
  let current = "";

  function generate(): void {
    const { logos, skipped } = scanLogos(root);
    const source = render(logos);
    if (skipped.length) {
      console.warn(`[partner-logos] skipped (not a readable logo image): ${skipped.join(", ")}`);
    }
    if (source === current) return;
    current = source;
    const target = path.join(root, GENERATED);
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, source);
  }

  return {
    name: "skyline-partner-logos",
    configResolved(config) {
      root = config.root;
    },
    buildStart() {
      generate();
    },
    configureServer(server) {
      generate();
      const dir = path.join(root, LOGO_DIR);
      server.watcher.add(dir);
      const onChange = (changed: string) => {
        if (path.resolve(path.dirname(changed)) === path.resolve(dir)) generate();
      };
      server.watcher.on("add", onChange);
      server.watcher.on("unlink", onChange);
      server.watcher.on("change", onChange);
    },
  };
}
