import { useEffect, useRef } from "react";
import { gsap, EASE, prefersReducedMotion } from "../gsap";
import { companyInfo } from "../data";
import { LegalToc, type TocItem } from "./LegalToc";
import { LegalSection, LegalList } from "./LegalSection";

const toc: TocItem[] = [
  { id: "information-we-collect", label: "1. Information We Collect" },
  { id: "how-we-use-information", label: "2. How We Use Information" },
  { id: "investment-business-enquiries", label: "3. Investment & Business Enquiries" },
  { id: "sharing-of-information", label: "4. Sharing of Information" },
  { id: "data-security", label: "5. Data Security" },
  { id: "data-retention", label: "6. Data Retention" },
  { id: "your-rights", label: "7. Your Rights" },
  { id: "third-party-links", label: "8. Third-Party Links" },
  { id: "contact", label: "9. Contact" },
  { id: "changes-to-this-policy", label: "10. Changes to This Policy" },
];

export function PrivacyContent() {
  const rootRef = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!rootRef.current) return;
    const reduce = prefersReducedMotion();

    const ctx = gsap.context(() => {
      if (reduce) {
        gsap.set(".ls-section", { opacity: 1, y: 0 });
        return;
      }
      gsap.utils.toArray<HTMLElement>(".ls-section").forEach((el) => {
        gsap.fromTo(
          el,
          { opacity: 0, y: 16 },
          { opacity: 1, y: 0, duration: 0.6, ease: EASE.out3, scrollTrigger: { trigger: el, start: "top 88%" } },
        );
      });
    }, rootRef);

    return () => ctx.revert();
  }, []);

  return (
    <section ref={rootRef} className="relative bg-[#F8F7F3] py-20 md:py-24">
      <div className="mx-auto max-w-[1600px] px-6 md:px-10">
        <div className="grid gap-12 lg:grid-cols-12 lg:gap-14">
          <LegalToc items={toc} />

          <div className="lg:col-span-9 lg:max-w-[760px]">
            <LegalSection id="information-we-collect" number="01" title="Information We Collect">
              <p>
                We may collect information you provide directly, as well
                as limited technical information generated by your use of
                the website.
              </p>
              <LegalList
                items={[
                  "Information submitted through our contact forms, including your name, email address, company or organization and enquiry details",
                  "Technical information such as browser type, device and IP address, where applicable",
                ]}
              />
            </LegalSection>

            <LegalSection id="how-we-use-information" number="02" title="How We Use Information">
              <p>We use the information we collect to:</p>
              <LegalList
                items={[
                  "Respond to enquiries and communicate with investors, partners and business contacts",
                  "Operate, maintain and improve the website",
                  "Maintain the security and integrity of our systems",
                  "Comply with applicable legal and regulatory obligations",
                ]}
              />
            </LegalSection>

            <LegalSection id="investment-business-enquiries" number="03" title="Investment & Business Enquiries">
              <p>
                Where you submit information in connection with
                investment opportunities, investor relations, strategic
                partnerships, strategic advisory or management services,
                that information may be reviewed by relevant members of
                the Skyline Holding team for the purpose of evaluating
                and responding to your enquiry.
              </p>
            </LegalSection>

            <LegalSection id="sharing-of-information" number="04" title="Sharing of Information">
              <p>
                Skyline Holding does not sell personal information.
                Information may be shared, where necessary, with:
              </p>
              <LegalList
                items={[
                  "Professional advisers, including legal, financial and compliance advisers",
                  "Service and technology providers who support our operations",
                  "Legal or regulatory authorities, where required by law",
                ]}
              />
            </LegalSection>

            <LegalSection id="data-security" number="05" title="Data Security">
              <p>
                We apply reasonable technical and organizational measures
                designed to protect information against unauthorized
                access, loss or misuse. No method of transmission or
                storage is entirely secure, and we cannot guarantee
                absolute security.
              </p>
            </LegalSection>

            <LegalSection id="data-retention" number="06" title="Data Retention">
              <p>
                Information is retained only for as long as reasonably
                necessary for the purpose it was collected, ongoing
                business requirements or applicable legal obligations.
              </p>
            </LegalSection>

            <LegalSection id="your-rights" number="07" title="Your Rights">
              <p>
                Depending on the applicable law in your jurisdiction, you
                may have rights relating to your personal information,
                which may include the right to access, correct, delete,
                restrict or object to processing, and to data
                portability. Where such rights apply, requests can be
                directed to us using the contact details below.
              </p>
            </LegalSection>

            <LegalSection id="third-party-links" number="08" title="Third-Party Links">
              <p>
                Our website may contain links to third-party websites. We
                are not responsible for the privacy practices or content
                of those websites and encourage you to review their
                respective policies.
              </p>
            </LegalSection>

            <LegalSection id="contact" number="09" title="Contact">
              <p>Questions regarding this Privacy Policy can be directed to:</p>
              <div className="border border-[#12161B]/10 bg-white/60 px-6 py-5">
                <p className="font-[Inter] text-[14px] font-semibold text-[#12161B]">
                  {companyInfo.legalName}
                </p>
                <p className="mt-1 whitespace-pre-line font-[Inter] text-[13.5px] leading-[1.6] text-[#12161B]/65">
                  {companyInfo.registeredAddress}
                </p>
                <p className="mt-2 break-all font-[Inter] text-[13.5px] leading-[1.6] text-[#12161B]/65">
                  Email:{" "}
                  <a href={`mailto:${companyInfo.email}`} className="font-medium text-[#12161B] underline decoration-[#12161B]/25 underline-offset-4 transition-colors hover:text-[#C7A86B] hover:decoration-[#C7A86B]">
                    {companyInfo.email}
                  </a>
                </p>
              </div>
            </LegalSection>

            <LegalSection id="changes-to-this-policy" number="10" title="Changes to This Policy">
              <p>
                We may update this Privacy Policy from time to time. The
                current version will always be available on this page.
              </p>
            </LegalSection>
          </div>
        </div>
      </div>
    </section>
  );
}
