// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/AboutPage.tsx": () => import("../components/mockups/AboutPage.tsx"),
  "./components/mockups/ContactPage.tsx": () => import("../components/mockups/ContactPage.tsx"),
  "./components/mockups/GovernancePage.tsx": () => import("../components/mockups/GovernancePage.tsx"),
  "./components/mockups/ImpressumPage.tsx": () => import("../components/mockups/ImpressumPage.tsx"),
  "./components/mockups/InvestmentOpportunitiesPage.tsx": () => import("../components/mockups/InvestmentOpportunitiesPage.tsx"),
  "./components/mockups/InvestmentSectorsPage.tsx": () => import("../components/mockups/InvestmentSectorsPage.tsx"),
  "./components/mockups/InvestmentStrategyPage.tsx": () => import("../components/mockups/InvestmentStrategyPage.tsx"),
  "./components/mockups/InvestorRelationsPage.tsx": () => import("../components/mockups/InvestorRelationsPage.tsx"),
  "./components/mockups/LeadershipPage.tsx": () => import("../components/mockups/LeadershipPage.tsx"),
  "./components/mockups/LegalPage.tsx": () => import("../components/mockups/LegalPage.tsx"),
  "./components/mockups/ManagementServicesPage.tsx": () => import("../components/mockups/ManagementServicesPage.tsx"),
  "./components/mockups/PrivacyPage.tsx": () => import("../components/mockups/PrivacyPage.tsx"),
  "./components/mockups/SkylineHomepage.tsx": () => import("../components/mockups/SkylineHomepage.tsx"),
  "./components/mockups/StrategicAdvisoryPage.tsx": () => import("../components/mockups/StrategicAdvisoryPage.tsx"),
  "./components/mockups/StrategicPartnershipsPage.tsx": () => import("../components/mockups/StrategicPartnershipsPage.tsx"),
  "./components/mockups/TermsPage.tsx": () => import("../components/mockups/TermsPage.tsx")
};
