// AUTO-GENERATED by partnerLogosPlugin.ts from public/images/partners. Do not edit by hand.
export const partnerLogoFiles: ReadonlyArray<{ file: string; width: number; height: number }> = [
  { file: "imgi_6_ChatGPT-Image-Jul-21-2026-01_24_39-AM.png", width: 2172, height: 724 },
  { file: "imgi_7_Mercedes-Benz_Logo_2010.svg", width: 1399.61, height: 354.33 },
  { file: "imgi_8_Sauber_Motorsport_2023_logo.png", width: 304, height: 58 },
  { file: "imgi_9_Allianz.svg.webp", width: 960, height: 239 },
  { file: "imgi_10_Telekom_Logo_2013.svg-scaled.webp", width: 2560, height: 1257 },
  { file: "imgi_11_UBS_Logo.png", width: 1280, height: 469 },
  { file: "imgi_12_3840px-Newmont_Corporation_-_Logo.svg.png", width: 3840, height: 624 },
  { file: "imgi_13_Vodafone_2017_logo.svg.webp", width: 960, height: 255 },
  { file: "imgi_14_shell-logo.png", width: 1000, height: 932 },
];
